language: java
sudo: false
addons:
  sonarcloud:
    organization: wojciechzankowski-github
jdk:
  - openjdk11
script:
  - if [ $TRAVIS_BRANCH == 'master' ];
    then
      mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -P javadoc;
    else
      mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar;
    fi
after_success:
  - bash ./scripts/deploy.sh
  - bash <(curl -s https://codecov.io/bash)
